unbind = SUPER, G

# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

# Normal SUPER binds
# bind = SUPER, A, exec, omarchy-launch-or-focus "ai-chat" "$terminal --title=ai-chat -e bash -c 'nvim +AiToggle'"
bind = SUPER, A, exec, omarchy-launch-or-focus "ai-chat" "$terminal --title=ai-chat -e bash -ic 'cd /home/mirco && cld'"
# bindd = SUPER, A, Chrome, exec, $terminal --working-directory="
bind = SUPER, P, exec, omarchy-launch-or-focus "project-main" "$terminal --title=project-main -e bash -c 'cd $HOME/projects/MediaLib && nvim .'"
unbind = SUPER, T # shouldnt be necessary, but I broke something idk
bindd = SUPER, T, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, G, Github-Desktop, exec, omarchy-launch-or-focus "github-desktop -disable-gpu"
# bindd = SUPER, B, Chrome, exec, $browser
#
bind = SUPER, B, exec, omarchy-launch-or-focus "chromium" "chromium"
# bindd = SUPER, B, Chrome, exec, omarchy-launch-or-focus "chromium" $browser
# bindd = SUPER, N, Editor, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime" 

bindd = SUPER, N, Editor, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"; #sleep 2.2; hyprctl dispatch resizeactive exact 200 800

# For some reason shift, I can probably move them to be more direct
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bind = SUPER SHIFT, D, exec, omarchy-launch-or-focus "lazydocker" "$terminal --title=lazydocker --working-directory=~ -e lazydocker"

# WebApps
bindd = SUPER, Y, Music, exec, omarchy-launch-or-focus-webapp Music "https://music.youtube.com/"
bindd = SUPER, D, Discord, exec, omarchy-launch-or-focus-webapp Discord "https://discord.com/app"

# Super Alt for config stuff holy
# Singleton of a terminal or any window, the omarchy name and window title need to be the same
bind = SUPER ALT, N, exec, omarchy-launch-or-focus "nvim-cfg" "$terminal --title=nvim-cfg -e bash -c 'cd ~/.config/nvim && nvim lua/config/keymaps.lua'"
bind = SUPER ALT, H, exec, omarchy-launch-or-focus "hyp-cfg" "$terminal --title=hyp-cfg -e bash -c 'cd /home/mirco/.config/hypr && nvim hyprland.conf'"
bind = SUPER ALT, B, exec, omarchy-launch-or-focus "bashrc-cfg" "$terminal --title=bashrc-cfg -e bash -c 'cd ~ && nvim .bashrc'"


#unbind = SUPER, S
# Menu easier
unbind = SUPER, SPACE
bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

# DHH Notes
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
# bindd = SUPER SHIFT ALT, C, Browser (private), exec, $browser --private
