# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf
source = ~/.config/hypr/tiling-mirco.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu

workspace = 1, monitor:DP-4, default:true
workspace = 2, monitor:DP-4
workspace = 3, monitor:DP-4
workspace = 4, monitor:DP-4
workspace = 5, monitor:DP-4

workspace = 6, monitor:DP-5, default:true
workspace = 6, layout:master, layoutopt:mfact:0.8
workspace = 7, monitor:DP-5
workspace = 8, monitor:DP-5
workspace = 9, monitor:DP-5


workspace = 1, layout:master, layoutopt:orientation:right



# place things on 2nd monitor and set workspace, actually these workspaces are always monitor 2 so bwam
windowrulev2 = workspace 6, class:^obsidian$
windowrulev2 = workspace 8, initialTitle:^discord.com_/app$
windowrulev2 = workspace 8, initialTitle:^music.youtube.com_/$


# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia


misc {
  size_limits_tiled = true
}
