
unbind = SUPER, J
unbind = CTRL SHIFT, I
unbind = SUPER, K
unbind = SUPER_CTRL, I

bindd = ALT, TAB, Toggle last 2 windows, focuscurrentorlast
bindd = SUPER, U, Toggle window split, togglesplit

# Move focus with SUPER + arrow keys
bindd = SUPER, J, Move window focus left, movefocus, l
bindd = SUPER, L, Move window focus right, movefocus, r
bindd = SUPER, I, Move window focus up, movefocus, u
bindd = SUPER, K, Move window focus down, movefocus, d

# Switch workspaces with SUPER + [1-9]
bindd = SUPER ,F1, Switch to workspace 1, workspace, 1
# First Super press enters submap with timeout
bind = SUPER, SUPER, submap, doubletap
submap = doubletap
# Second Super press within timeout switches workspace
bind = , SUPER, workspace, 1
bind = , SUPER, submap, reset
# Timeout automatically resets submap after delay
submap = reset
bindd = SUPER ,F2, Switch to workspace 2, workspace, 2
bindd = SUPER ,F3, Switch to workspace 3, workspace, 3
bindd = SUPER ,F4, Switch to workspace 4, workspace, 4
bindd = SUPER ,F5, Switch to workspace 5, workspace, 5
bindd = SUPER ,F6, Switch to workspace 6, workspace, 6
bindd = SUPER ,F7, Switch to workspace 7, workspace, 7
bindd = SUPER ,F8, Switch to workspace 8, workspace, 8

# Swap active window with the one next to it with SUPER + SHIFT + arrow keys
bindd = SUPER SHIFT, J, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, I, Swap window up, swapwindow, u
bindd = SUPER SHIFT, K, Swap window down, swapwindow, d

# Move active window to a workspace with SUPER + SHIFT + [1-9]
bindd = SUPER SHIFT, F1, Move window to workspace 1, movetoworkspace, 1
bindd = SUPER SHIFT, F2, Move window to workspace 2, movetoworkspace, 2
bindd = SUPER SHIFT, F3, Move window to workspace 3, movetoworkspace, 3
bindd = SUPER SHIFT, F4, Move window to workspace 4, movetoworkspace, 4
bindd = SUPER SHIFT, F5, Move window to workspace 5, movetoworkspace, 5
bindd = SUPER SHIFT, F6, Move window to workspace 6, movetoworkspace, 6
bindd = SUPER SHIFT, F7, Move window to workspace 7, movetoworkspace, 7
bindd = SUPER SHIFT, F8, Move window to workspace 8, movetoworkspace, 8

# bindd = SUPER ALT, L, Expand window right, resizeactive, -100,0
 
# bindd = SUPER, V, Toggle floating, toggleFloating
# bind = SUPER SHIFT, P, pin, active 

# cycle through active workspaces on the current monitors
bind = SUPER CTRL, J, workspace, m-1
bind = SUPER CTRL, L, workspace, m+1


# Resize active window
bind = SUPER_CTRL SHIFT, k, resizeactive, 0 100      # grow down
bind = SUPER_CTRL SHIFT, i, resizeactive, 0 -100     # shrink down / grow up  
bind = SUPER_CTRL SHIFT, l, resizeactive, 100 0      # grow right
bind = SUPER_CTRL SHIFT, j, resizeactive, -100 0     # shrink right / grow left


bind = SUPER , M, exec, ~/.config/hypr/scripts/smart_master_swap.sh
# bind = SUPER, M, exec, hyprctl dispatch focuscurrentorlast # works as expected now...
# bind = SUPER, M, exec, hyprctl dispatch layoutmsg swapwithmaster # works as expected now...
# bind = SUPER, M, exec, hyprctl dispatch layoutmsg swapwithmaster && sleep 0.5 && hyprctl dispatch layoutmsg focusmaster
#
#
bind = SUPER, U, layoutmsg, addmaster
bind = SUPER, U, layoutmsg, removemaster

master {
    new_on_active = before
}

